In [1]:
from pathlib import Path
import pandas as pd
import scipy.stats as stats
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Create a file path
census_data = pd.read_csv("Resources/census_data_clean_medgross.csv")

# Read in the data. 
census_data.head()

,Owner_Occupied_Units,Owner_White_alone,Owner_Black_African_American_alone,Owner_American_Indian_Alaska_Native_alone,Owner_Asian_alone,Owner_Native_Hawaiian_Other_Pacific_Islander_alone,Owner_Some_other_race_alone,Owner_Two_or_more_races,Owner_White_no_Hispanic_or_Latino,Owner_Hispanic_Latino,...,Black_African_American,American_Indian_Alaska_Native,Asian,Native_Hawaiian_Other_Pacific_Islander,Other_Race,Two_More_Races,Count_Inds_Income_Past_12_Mos_<_Pov_Level,state,Zip_code,year
0,265,265,0,0,0,0,0,0,265,0,...,0,0,0,0,0,0,771,NaN,40771,2020
1,418,398,0,3,0,0,8,9,398,11,...,0,3,0,0,16,16,166,NaN,73547,2020
2,352,352,0,0,0,0,0,0,344,8,...,21,0,0,0,0,0,156,NaN,58788,2021
3,333,333,0,0,0,0,0,0,333,0,...,19,0,0,0,0,0,118,NaN,58788,2022
4,7,7,0,0,0,0,0,0,7,0,...,0,0,0,0,0,0,8,30.0,59025,2019

In [4]:
# Median household income over time
# Group by year and calculate the mean owner-occupancy rate for each year
median_gross_rent = census_data.groupby('year')['Median_Gross_Rent'].median()
median_gross_rent

year
2019    814.0
2020    831.0
2021    871.0
2022    944.0
Name: Median_Gross_Rent, dtype: float64

In [ ]:


# Median household income over time
# Median gross rent over time
# Median monthly owner cost over time